/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_go_rra_swc_system_dps_iplot_jni_IGnuPlot */

#ifndef _Included_com_tobee_iplot_jni_IGnuPlot
#define _Included_com_tobee_iplot_jni_IGnuPlot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_go_rra_swc_system_dps_iplot_jni_IGnuPlot
 * Method:    initIGnuPlotCmd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tobee_iplot_jni_IGnuPlot_initIGnuPlotCmd
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kr_go_rra_swc_system_dps_iplot_jni_IGnuPlot
 * Method:    gnuPlotCmd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tobee_iplot_jni_IGnuPlot_gnuPlotCmd
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kr_go_rra_swc_system_dps_iplot_jni_IGnuPlot
 * Method:    gnuPlotCmdScript
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tobee_iplot_jni_IGnuPlot_gnuPlotCmdScript
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     kr_go_rra_swc_system_dps_iplot_jni_IGnuPlot
 * Method:    gnuPlotClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tobee_iplot_jni_IGnuPlot_gnuPlotClose
  (JNIEnv *, jclass);

/*
 * Class:     kr_go_rra_swc_system_dps_iplot_jni_IGnuPlot
 * Method:    gnuPlotCmdBytes
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_tobee_iplot_jni_IGnuPlot_gnuPlotCmdBytes
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
